import erarpc

# 与机器人控制器建立连接，连接成功返回一个机器人对象
robot = erarpc.RPC('192.168.58.2')

# 查询状态
ret = robot.GetRobotInstallAngle()
print(ret)
ret = robot.GetActualJointPosDegree(0)
print(ret)
ret = robot.GetActualJointPosRadian(0)
print(ret)
ret = robot.GetActualTCPPose(0)
print(ret)
ret = robot.GetActualTCPNum(0)
print(ret)
ret = robot.GetActualWObjNum(0)
print(ret)
ret = robot.GetActualToolFlangePose(0)
print(ret)
ret = robot.GetJointTorques(0)
print(ret)
ret = robot.GetTargetPayload(0)
print(ret)
ret = robot.GetTargetPayloadCog(0)
print(ret)
ret = robot.GetRobotCurJointsConfig()
print(ret)
ret = robot.GetSystemClock()
print(ret)
ret = robot.GetDefaultTransVel()
print(ret)
ret = robot.GetTCPOffset(0)
print(ret)
ret = robot.GetWObjOffset(0)
print(ret)
ret = robot.GetJointSoftLimitDeg(0)
print(ret)

J1=[95.442,-101.149,-98.699,-68.347,90.580,-47.174]
P1=[75.414,568.526,338.135,-178.348,-0.930,52.611]
ret = robot.GetInverseKin(0,P1,-1)
print(ret)
ret = robot.GetInverseKinRef(0,P1,J1)
print(ret)
ret = robot.GetInverseKinHasSolution(0,P1,J1)
print(ret)
ret = robot.GetForwardKin(J1)
print(ret)
ret = robot.GetRobotInstallAngle()
print(ret)