# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fr3_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  gains:
    j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1