# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 125
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
   sim_control_mode: 0 # 0: position, 1: velocity

position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
   constraints:
      goal_time: 2.0
   state_publish_rate: 100


# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50

# Group Position Controllers ---------------------------------------
# Allows to send single ROS msg of Float64MultiArray to all joints
joint_position_controller:
   type: ur5_robotiq_85_simulation/JointPositionController
   arm_id: fr3_arm
   joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
   gains: [
      1, 1, 1, 1, 1, 1
   ]
      
gazebo_ros_control:
   pid_gains:
      j1:
         p: 100.0
         i: 0.01
         d: 10.0
      j2:
         p: 100.0
         i: 0.01
         d: 10.0
      j3:
         p: 100.0
         i: 0.01
         d: 10.0
      j4:
         p: 100.0
         i: 0.01
         d: 10.0
      j5:
         p: 100.0
         i: 0.01
         d: 10.0
      j6:
         p: 100.0
         i: 0.01
         d: 10.0


