controller_list:
  - name: fake_fr10_arm_controller
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
initial:  # Define initial robot poses.
  - group: fr10_arm
    pose: home