# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fr10_arm
  joint_model_group_pose: home
  
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  sim_control_mode: 1  # 0: position, 1: velocity

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

fr10_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  gains: # Required because we're controlling an effort interface
    j1: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    j2: {p: 6000,  d: 40, i: 1, i_clamp: 1}
    j3: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    j4: {p: 500,  d: 1, i: 1, i_clamp: 1}
    j5: {p: 500,  d: 1, i: 1, i_clamp: 1}
    j6: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints:
    goal_time: 1.6
    stopped_velocity_tolerance: 0.5
    j1: {trajectory: 0.1, goal: 0.1}
    j2: {trajectory: 0.1, goal: 0.1}
    j3: {trajectory: 0.1, goal: 0.1}
    j4: {trajectory: 0.1, goal: 0.1}
    j5: {trajectory: 0.1, goal: 0.1}
    j6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

controller_list:
  - name: fr10_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6

arm_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6

gazebo_ros_control:
   pid_gains:
      j1:
         p: 2000.0
         i: 0.1
         d: 10.0
      j2:
         p: 2000.0
         i: 0.1
         d: 10.0
      j3:
         p: 2000.0
         i: 0.1
         d: 10.0
      j4:
         p: 2000.0
         i: 0.1
         d: 10.0
      j5:
         p: 2000.0
         i: 0.1
         d: 10.0
      j6:
         p: 10000.0
         i: 0.5
         d: 0.05
